name: coa-connectivity
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas>=1.1
  - rioxarray>=0.19
  - xarray
  - rasterio
  - pyproj
  - shapely
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - requests
  - jupyter
  - ipykernel
  - nbconvert
